"""
ML PIPELINE PHASE 14 -- EXPERIMENTAL PROBABILITY RECALIBRATION FEASIBILITY
(RESEARCH ONLY).

Determines whether probability calibration improves the interpretability of the
frozen binary LR screening probability. The underlying LogisticRegression model
is NEVER retrained or changed; calibration is applied only to its probability
outputs. No production code, artifact, threshold, frontend, or SHAP is modified.
No commit, no push.

Models compared (on probability outputs only):
  A. Raw probabilities
  B. Sigmoid / Platt calibration
  C. Isotonic calibration

Discipline:
  - Canonical 112 training / 38 outer-test subject split (zero overlap).
  - OOF raw probabilities for the 112 dev subjects via StratifiedGroupKFold(5,
    shuffle=True, random_state=42) grouped by Subject ID, latest available visit
    by MR Delay (production visit policy). Exactly one OOF probability per dev
    subject, generated by a model that did not train on that subject.
  - Calibration method selection via a SECOND-LEVEL grouped 5-fold CV on the 112
    dev subjects: in each fold the calibrator is fit on calibration-training
    subjects' OOF probs and applied to calibration-validation subjects. Never fit
    and evaluate on the same subject.
  - Outer 38 subjects used exactly once for the final comparison; never used to
    fit/select calibrator, tune parameters, or select thresholds.
"""

from pathlib import Path
import json
import platform

import numpy as np
import pandas as pd

from sklearn.calibration import _SigmoidCalibration
from sklearn.isotonic import IsotonicRegression
from sklearn.linear_model import LogisticRegression
from sklearn.impute import SimpleImputer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import StratifiedGroupKFold
from sklearn.metrics import (
    accuracy_score, balanced_accuracy_score, confusion_matrix, f1_score,
    precision_score, recall_score, roc_auc_score, average_precision_score,
    brier_score_loss, log_loss,
)

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

import sklearn

DATA_PATH = Path(__file__).resolve().parents[1] / "data" / "raw" / "Dataset.csv"
SPLIT_PATH = Path(__file__).resolve().parents[1] / "models" / "experiments" / "subject_grouped_baseline" / "subject_split.json"
PROD_ARTIFACT = Path(__file__).resolve().parents[1] / "models" / "production" / "binary_lr_latest_visit_v1.pkl"
OUT_DIR = Path(__file__).resolve().parents[1] / "models" / "experiments" / "phase14_recalibration"

SEX_MAP = {"M": 1, "F": 0}
GROUP_MAP = {"Nondemented": 0, "Converted": 1, "Demented": 2}
SUBJECT_COL = "Subject ID"
LABEL_COL = "group"
BINARY_COL = "binary_target"
MR_DELAY_COL = "mr_delay"
FEATURES = ["age", "sex", "education_years", "mmse", "ses"]

THRESHOLD_RAW = 0.40
N_FOLDS = 5
CV_RANDOM_STATE = 42
NP_SEED = 42
EXPECTED_MD5 = "8FC95A3838FFF665CF47FA55C4322096"

WINNER_HP = {"clf__C": 10.0, "clf__class_weight": "balanced"}

BINS = [
    (0.00, 0.10, "< 0.10"), (0.10, 0.20, "0.10-0.19"), (0.20, 0.30, "0.20-0.29"),
    (0.30, 0.40, "0.30-0.39"), (0.40, 0.50, "0.40-0.49"), (0.50, 0.60, "0.50-0.59"),
    (0.60, 0.70, "0.60-0.69"), (0.70, 0.80, "0.70-0.79"), (0.80, 0.90, "0.80-0.89"),
    (0.90, 0.95, "0.90-0.94"), (0.95, 0.99, "0.95-0.99"), (0.99, 1.01, ">= 0.99"),
]


def md5_hex(path):
    import hashlib
    h = hashlib.md5()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(65536), b""):
            h.update(chunk)
    return h.hexdigest().upper()


def load_data():
    df = pd.read_csv(DATA_PATH)
    df = df.rename(columns={
        "Age": "age", "M/F": "sex", "EDUC": "education_years",
        "MMSE": "mmse", "SES": "ses", "Group": LABEL_COL,
        "Visit": "raw_visit", "MR Delay": MR_DELAY_COL,
    })
    df["sex"] = df["sex"].map(SEX_MAP)
    df[LABEL_COL] = df[LABEL_COL].map(GROUP_MAP)
    df[BINARY_COL] = (df[LABEL_COL] != 0).astype(int)
    df = df.sort_values([SUBJECT_COL, MR_DELAY_COL]).reset_index(drop=True)
    return df


def latest_frame(subset):
    m = subset[subset[MR_DELAY_COL] == subset.groupby(SUBJECT_COL)[MR_DELAY_COL].transform("max")].copy()
    return m.reset_index(drop=True)


def make_pipeline():
    return Pipeline([
        ("imputer", SimpleImputer(strategy="median")),
        ("scaler", StandardScaler()),
        ("clf", LogisticRegression(max_iter=3000, solver="lbfgs", random_state=42)),
    ]).set_params(**WINNER_HP)


def ece(y_true, y_prob, n_bins=10):
    y_prob = np.asarray(y_prob); y_true = np.asarray(y_true)
    bins = np.linspace(0.0, 1.0, n_bins + 1)
    total = 0.0
    for lo, hi in zip(bins[:-1], bins[1:]):
        if hi == 1.0:
            m = (y_prob >= lo) & (y_prob <= hi)
        else:
            m = (y_prob >= lo) & (y_prob < hi)
        if m.sum() == 0:
            continue
        total += (m.sum() / len(y_true)) * abs(y_true[m].mean() - y_prob[m].mean())
    return float(total)


def metrics(y, p, t=THRESHOLD_RAW):
    y = np.asarray(y); p = np.asarray(p)
    y_pred = (p >= t).astype(int)
    tn, fp, fn, tp = confusion_matrix(y, y_pred, labels=[0, 1]).ravel()
    sens = tp / (tp + fn) if (tp + fn) else 0.0
    spec = tn / (tn + fp) if (tn + fp) else 0.0
    ppv = tp / (tp + fp) if (tp + fp) else 0.0
    npv = tn / (tn + fn) if (tn + fn) else 0.0
    uniq = len(np.unique(y))
    return {
        "n": int(len(y)), "positive": int((y == 1).sum()), "negative": int((y == 0).sum()),
        "sensitivity": float(sens), "specificity": float(spec),
        "balanced_accuracy": float((sens + spec) / 2),
        "ppv": float(ppv), "npv": float(npv),
        "f1": float(f1_score(y, y_pred, zero_division=0)),
        "accuracy": float(accuracy_score(y, y_pred)),
        "roc_auc": float(roc_auc_score(y, p)) if uniq == 2 else None,
        "pr_auc": float(average_precision_score(y, p)) if uniq == 2 else None,
        "brier": float(brier_score_loss(y, p)),
        "logloss": float(log_loss(y, p, labels=[0, 1])),
        "ece_10": ece(y, p),
        "tp": int(tp), "fp": int(fp), "tn": int(tn), "fn": int(fn),
        "min": float(p.min()), "max": float(p.max()),
        "mean": float(p.mean()), "median": float(np.median(p)),
    }


def bins_table(y, p):
    y = np.asarray(y); p = np.asarray(p)
    rows = []
    for lo, hi, label in BINS:
        if hi > 1.0:
            m = p >= lo
        else:
            m = (p >= lo) & (p < hi)
        n = int(m.sum())
        act_pos = int(y[m].sum())
        rows.append({
            "probability_range": label, "n": n, "actual_positive": act_pos,
            "actual_negative": n - act_pos,
            "observed_positive_rate": (float(y[m].mean()) if n else None),
            "mean_predicted_probability": (float(p[m].mean()) if n else None),
        })
    return rows


def reliability_fig(y, probs_dict, title, path):
    fig, ax = plt.subplots(figsize=(6.5, 6.5))
    ax.plot([0, 1], [0, 1], "k--", label="Perfect calibration")
    colors = {"raw": "tab:blue", "sigmoid": "tab:green", "isotonic": "tab:orange"}
    for name, p in probs_dict.items():
        p = np.asarray(p)
        n_bins = 5
        edges = np.linspace(0.0, 1.0, n_bins + 1)
        centers = (edges[:-1] + edges[1:]) / 2
        freqs = []
        for lo, hi in zip(edges[:-1], edges[1:]):
            if hi == 1.0:
                m = (p >= lo) & (p <= hi)
            else:
                m = (p >= lo) & (p < hi)
            freqs.append(np.asarray(y)[m].mean() if m.sum() else np.nan)
        ax.plot(centers, freqs, "o-", color=colors.get(name, "tab:gray"),
                label=name.capitalize())
    ax.set_xlabel("Mean predicted screening probability")
    ax.set_ylabel("Observed positive rate")
    ax.set_xlim(0, 1); ax.set_ylim(0, 1)
    ax.set_title(title + " — n=%d" % len(np.asarray(y)))
    ax.legend(loc="upper left")
    fig.tight_layout()
    fig.savefig(path, dpi=150)
    plt.close(fig)


def fit_calibrator(method, y, p):
    p = np.asarray(p)
    if method == "sigmoid":
        cal = _SigmoidCalibration()
        cal.fit(p.reshape(-1, 1), y)
        return ("sigmoid", cal)
    if method == "isotonic":
        iso = IsotonicRegression(out_of_bounds="clip")
        iso.fit(p, y)
        return ("isotonic", iso)
    return ("raw", None)


def apply_calibrator(fitted, p):
    name, cal = fitted
    p = np.asarray(p)
    if name == "raw":
        return p
    if name == "sigmoid":
        return cal.predict(p.reshape(-1, 1))
    return cal.predict(p)


def main():
    np.random.seed(NP_SEED)
    OUT_DIR.mkdir(parents=True, exist_ok=True)

    # production artifact untouched-check
    actual_md5 = md5_hex(PROD_ARTIFACT)
    print("Production artifact md5:", actual_md5, "| expected:", EXPECTED_MD5)
    assert actual_md5 == EXPECTED_MD5

    split = json.loads(SPLIT_PATH.read_text(encoding="utf-8"))
    train_subjects = sorted(split["train_subjects"])
    test_subjects = sorted(split["test_subjects"])
    assert len(set(train_subjects) & set(test_subjects)) == 0
    assert len(train_subjects) == 112 and len(test_subjects) == 38

    df = load_data()
    df_train = df[df[SUBJECT_COL].isin(train_subjects)]
    df_test = df[df[SUBJECT_COL].isin(test_subjects)]
    tr_latest = latest_frame(df_train)
    te_latest = latest_frame(df_test)
    assert len(tr_latest) == 112 and len(te_latest) == 38

    # ---------------- 3. OOF raw probabilities (dev) ----------------
    cv = StratifiedGroupKFold(n_splits=N_FOLDS, shuffle=True, random_state=CV_RANDOM_STATE)
    dev_meta = pd.DataFrame({"subject_id": tr_latest[SUBJECT_COL].to_numpy(),
                             "label": tr_latest[BINARY_COL].to_numpy()})
    folds = list(cv.split(dev_meta, dev_meta["label"], groups=dev_meta["subject_id"]))

    oof_parts = []
    for k, (tr_idx, va_idx) in enumerate(folds):
        tr_subj = set(dev_meta.iloc[tr_idx]["subject_id"])
        va_subj = set(dev_meta.iloc[va_idx]["subject_id"])
        assert not (tr_subj & va_subj)
        tr_rows = tr_latest[tr_latest[SUBJECT_COL].isin(tr_subj)]
        va_rows = tr_latest[tr_latest[SUBJECT_COL].isin(va_subj)]
        est = make_pipeline()
        est.fit(tr_rows[FEATURES], tr_rows[BINARY_COL])
        va_rows = va_rows.copy()
        va_rows["oof_raw_prob"] = est.predict_proba(va_rows[FEATURES])[:, 1]
        va_rows["oof_fold"] = k
        oof_parts.append(va_rows[[SUBJECT_COL, BINARY_COL, LABEL_COL, "oof_raw_prob", "oof_fold"]])
    oof = pd.concat(oof_parts, ignore_index=True)
    assert len(oof) == 112
    assert oof[SUBJECT_COL].nunique() == 112
    assert not set(oof[SUBJECT_COL]) & set(test_subjects)
    oof.to_csv(OUT_DIR / "oof_raw_predictions.csv", index=False)
    print("OOF: 112 unique dev subjects, zero overlap, no outer subjects. "
          "Positive (Converted|Demented) in OOF:", int((oof[BINARY_COL] == 1).sum()),
          "| Converted-only in OOF:", int((oof[LABEL_COL] == 1).sum()))

    # ---------------- 4. second-level calibration CV ----------------
    cal_fold_rows = []
    cal_oof_parts = {m: [] for m in ["sigmoid", "isotonic"]}
    cal_oof_raw_parts = []
    for k, (tr_idx, va_idx) in enumerate(folds):
        tr_subj = set(dev_meta.iloc[tr_idx]["subject_id"])
        va_subj = set(dev_meta.iloc[va_idx]["subject_id"])
        cal_tr = oof[oof[SUBJECT_COL].isin(tr_subj)]
        cal_va = oof[oof[SUBJECT_COL].isin(va_subj)]
        fold_row = {"calibration_fold": k,
                    "calibration_train_n": len(cal_tr),
                    "calibration_train_positive": int((cal_tr[BINARY_COL] == 1).sum()),
                    "calibration_validation_n": len(cal_va),
                    "calibration_validation_positive": int((cal_va[BINARY_COL] == 1).sum())}
        for method in ["sigmoid", "isotonic"]:
            fitted = fit_calibrator(method, cal_tr[BINARY_COL], cal_tr["oof_raw_prob"])
            cv_prob = apply_calibrator(fitted, cal_va["oof_raw_prob"].to_numpy())
            part = cal_va.copy()
            part["calibrated_prob"] = cv_prob
            part["calibration_fold"] = k
            part["method"] = method
            cal_oof_parts[method].append(part)
            m = metrics(cal_va[BINARY_COL], cv_prob)
            fold_row[f"{method}_logloss"] = m["logloss"]
            fold_row[f"{method}_brier"] = m["brier"]
            fold_row[f"{method}_ece"] = m["ece_10"]
        # raw fold metrics for comparison
        m = metrics(cal_va[BINARY_COL], cal_va["oof_raw_prob"])
        fold_row["raw_logloss"] = m["logloss"]
        fold_row["raw_brier"] = m["brier"]
        fold_row["raw_ece"] = m["ece_10"]
        cal_fold_rows.append(fold_row)

    fold_df = pd.DataFrame(cal_fold_rows)
    fold_df.to_csv(OUT_DIR / "calibration_fold_metrics.csv", index=False)
    print("\nCalibration fold metrics:")
    print(fold_df.to_string(index=False))

    # aggregate dev-level calibration CV metrics
    dev_cal = {}
    for method in ["sigmoid", "isotonic"]:
        combined = pd.concat(cal_oof_parts[method], ignore_index=True)
        combined.to_csv(OUT_DIR / "calibrated_oof_predictions.csv" if False else
                        OUT_DIR / ("calibrated_oof_predictions_%s.csv" % method), index=False)
        dev_cal[method] = metrics(combined[BINARY_COL], combined["calibrated_prob"])
    dev_cal["raw"] = metrics(oof[BINARY_COL], oof["oof_raw_prob"])

    # raw OOF bins (dev)
    raw_bins_dev = pd.DataFrame(bins_table(oof[BINARY_COL], oof["oof_raw_prob"]))
    raw_bins_dev.to_csv(OUT_DIR / "probability_bins_raw_dev.csv", index=False)

    print("\n=== DEVELOPMENT CALIBRATION CV (honest OOF, 112 subjects) ===")
    for method in ["raw", "sigmoid", "isotonic"]:
        m = dev_cal[method]
        print("  %-8s logloss=%.4f brier=%.4f ece=%.4f range=[%.3f,%.3f]"
              % (method, m["logloss"], m["brier"], m["ece_10"], m["min"], m["max"]))

    # stability summary
    stability = {
        "sigmoid": {
            "logloss_mean": float(fold_df["sigmoid_logloss"].mean()),
            "logloss_std": float(fold_df["sigmoid_logloss"].std()),
            "brier_mean": float(fold_df["sigmoid_brier"].mean()),
            "brier_std": float(fold_df["sigmoid_brier"].std()),
        },
        "isotonic": {
            "logloss_mean": float(fold_df["isotonic_logloss"].mean()),
            "logloss_std": float(fold_df["isotonic_logloss"].std()),
            "brier_mean": float(fold_df["isotonic_brier"].mean()),
            "brier_std": float(fold_df["isotonic_brier"].std()),
        },
    }
    cv_metrics = {
        "n_dev_subjects": 112,
        "n_folds": N_FOLDS,
        "split": "StratifiedGroupKFold(5, shuffle, random_state=42) grouped by Subject ID",
        "raw": dev_cal["raw"],
        "sigmoid": dev_cal["sigmoid"],
        "isotonic": dev_cal["isotonic"],
        "stability": stability,
        "small_sample_note": ("Isotonic is potentially unstable: Converted total n=14; "
                              "calibration folds have few positives; do not choose isotonic "
                              "based on a single fold."),
    }
    (OUT_DIR / "calibration_cv_metrics.json").write_text(json.dumps(cv_metrics, indent=2), encoding="utf-8")

    # reliability diagrams (dev, calibration CV)
    reliability_fig(oof[BINARY_COL],
                    {"raw": oof["oof_raw_prob"],
                     "sigmoid": pd.concat(cal_oof_parts["sigmoid"], ignore_index=True)["calibrated_prob"],
                     "isotonic": pd.concat(cal_oof_parts["isotonic"], ignore_index=True)["calibrated_prob"]},
                    "Development reliability (calibration CV)", OUT_DIR / "reliability_dev.png")

    # ---------------- 7. OUTER TEST: final comparison ----------------
    # Method selection from development CV only (we report all three, then choose
    # based on dev evidence; sigmoid is the likely stable choice).
    print("\n=== OUTER TEST (38 subjects, once) ===")
    final_lr = make_pipeline()
    final_lr.fit(tr_latest[FEATURES], tr_latest[BINARY_COL])
    te = te_latest.copy()
    te["raw_prob"] = final_lr.predict_proba(te[FEATURES])[:, 1]

    outer = {"raw": metrics(te[BINARY_COL], te["raw_prob"])}
    for method in ["sigmoid", "isotonic"]:
        # fit calibrator on FULL dev OOF (per the protocol), apply once to outer
        fitted = fit_calibrator(method, oof[BINARY_COL], oof["oof_raw_prob"])
        pcal = apply_calibrator(fitted, te["raw_prob"].to_numpy())
        te["cal_prob_%s" % method] = pcal
        outer[method] = metrics(te[BINARY_COL], pcal)
    outer_rows = []
    for i, row in te.iterrows():
        outer_rows.append({
            "subject_id": row[SUBJECT_COL], "true_binary_label": int(row[BINARY_COL]),
            "raw_probability": round(float(row["raw_prob"]), 6),
            "sigmoid_probability": round(float(row["cal_prob_sigmoid"]), 6),
            "isotonic_probability": round(float(row["cal_prob_isotonic"]), 6),
        })
    (OUT_DIR / "outer_test_raw_vs_calibrated.csv").write_text(
        pd.DataFrame(outer_rows).to_csv(index=False), encoding="utf-8")

    print("  RAW      logloss=%.4f brier=%.4f ece=%.4f" % (outer["raw"]["logloss"], outer["raw"]["brier"], outer["raw"]["ece_10"]))
    for method in ["sigmoid", "isotonic"]:
        m = outer[method]
        print("  %-8s logloss=%.4f brier=%.4f ece=%.4f range=[%.3f,%.3f]"
              % (method, m["logloss"], m["brier"], m["ece_10"], m["min"], m["max"]))

    (OUT_DIR / "outer_test_metrics.json").write_text(json.dumps(outer, indent=2), encoding="utf-8")

    # reliability diagrams (outer)
    reliability_fig(te[BINARY_COL],
                    {"raw": te["raw_prob"],
                     "sigmoid": te["cal_prob_sigmoid"],
                     "isotonic": te["cal_prob_isotonic"]},
                    "Outer-test reliability (n=38)", OUT_DIR / "reliability_outer.png")

    # bins (outer) raw vs selected
    pb_raw = pd.DataFrame(bins_table(te[BINARY_COL], te["raw_prob"]))
    pb_raw.to_csv(OUT_DIR / "probability_bins_raw.csv", index=False)
    pb_sig = pd.DataFrame(bins_table(te[BINARY_COL], te["cal_prob_sigmoid"]))
    pb_sig.to_csv(OUT_DIR / "probability_bins_calibrated.csv", index=False)
    print("\nOuter bins RAW:")
    print(pb_raw.to_string(index=False))
    print("\nOuter bins SIGMOID:")
    print(pb_sig.to_string(index=False))

    # ---------------- 8. threshold mapping ----------------
    sig_fitted = fit_calibrator("sigmoid", oof[BINARY_COL], oof["oof_raw_prob"])
    mapped_threshold = float(apply_calibrator(sig_fitted, np.array([THRESHOLD_RAW]))[0])
    thresh_map = {
        "raw_threshold": THRESHOLD_RAW,
        "calibrated_threshold_equivalent_sigmoid": round(mapped_threshold, 4),
        "note": ("Option A: keep screening decision on RAW probability (raw >= 0.40); "
                 "calibrated probability displayed via sigmoid. The displayed threshold "
                 "boundary is the calibrated value at raw 0.40."),
    }
    (OUT_DIR / "threshold_mapping.json").write_text(json.dumps(thresh_map, indent=2), encoding="utf-8")
    print("\nThreshold mapping: raw 0.40 -> sigmoid-calibrated %.4f" % mapped_threshold)

    # ---------------- 9. screening decision comparison ----------------
    # Option A: raw decision is preserved (>= 0.40). Calibrated decision at mapped
    # threshold should reproduce the same flags (monotone transforms).
    dec = te[[SUBJECT_COL]].copy()
    dec["true_binary_label"] = te[BINARY_COL]
    dec["raw_probability"] = te["raw_prob"]
    dec["raw_screening"] = np.where(te["raw_prob"] >= THRESHOLD_RAW, "positive", "negative")
    dec["calibrated_sigmoid"] = te["cal_prob_sigmoid"]
    dec["calibrated_screening_at_mapped"] = np.where(te["cal_prob_sigmoid"] >= mapped_threshold,
                                                     "positive", "negative")
    dec["flags_changed"] = dec["raw_screening"] != dec["calibrated_screening_at_mapped"]
    n_changed = int(dec["flags_changed"].sum())
    dec.to_csv(OUT_DIR / "screening_decision_comparison.csv", index=False)
    print("\nScreening decision comparison (Option A): subjects whose flag would change =", n_changed)

    scr_raw = metrics(te[BINARY_COL], te["raw_prob"], t=THRESHOLD_RAW)
    scr_cal = metrics(te[BINARY_COL], te["cal_prob_sigmoid"], t=mapped_threshold)
    print("RAW screening @0.40: sens=%.3f spec=%.3f balacc=%.3f ppv=%.3f npv=%.3f f1=%.3f acc=%.3f"
          % (scr_raw["sensitivity"], scr_raw["specificity"], scr_raw["balanced_accuracy"],
             scr_raw["ppv"], scr_raw["npv"], scr_raw["f1"], scr_raw["accuracy"]))
    print("SIGMOID screening @mapped %.4f: sens=%.3f spec=%.3f balacc=%.3f"
          % (mapped_threshold, scr_cal["sensitivity"], scr_cal["specificity"], scr_cal["balanced_accuracy"]))
    (OUT_DIR / "screening_metrics_comparison.json").write_text(json.dumps({
        "raw_at_0.40": {k: scr_raw[k] for k in ["sensitivity", "specificity", "balanced_accuracy",
                                                "ppv", "npv", "f1", "accuracy", "roc_auc", "pr_auc"]},
        "sigmoid_at_mapped_threshold": {k: scr_cal[k] for k in ["sensitivity", "specificity",
                                                                "balanced_accuracy", "ppv", "npv",
                                                                "f1", "accuracy", "roc_auc", "pr_auc"]},
        "flags_changed_outer": n_changed,
        "note": "Option A preserves the raw 0.40 decision; sigmoid is monotone so flags should be identical.",
    }, indent=2), encoding="utf-8")

    # ---------------- 10. extreme / fixed case ----------------
    fx = pd.DataFrame([{"age": 74, "sex": 1, "education_years": 10, "mmse": 23, "ses": 1}])
    pfx_raw = float(final_lr.predict_proba(fx[FEATURES])[:, 1][0])
    pfx_sig = float(apply_calibrator(sig_fitted, np.array([pfx_raw]))[0])
    iso_fitted = fit_calibrator("isotonic", oof[BINARY_COL], oof["oof_raw_prob"])
    pfx_iso = float(apply_calibrator(iso_fitted, np.array([pfx_raw]))[0])
    fx_res = {
        "fixture": {"age": 74, "sex": 1, "education_years": 10, "mmse": 23, "ses": 1},
        "raw_probability": round(pfx_raw, 6),
        "sigmoid_probability": round(pfx_sig, 6),
        "isotonic_probability": round(pfx_iso, 6),
        "raw_screening_decision": "positive" if pfx_raw >= THRESHOLD_RAW else "negative",
        "calibrated_screening_decision_optionA": "positive" if pfx_sig >= mapped_threshold else "negative",
        "calibrated_threshold_equivalent_to_raw_0.40": round(mapped_threshold, 4),
        "note": ("Sanity-check fixture ONLY, not a validation sample. Do not judge the "
                 "calibration method based on this single case."),
    }
    (OUT_DIR / "fixed_case_comparison.json").write_text(json.dumps(fx_res, indent=2), encoding="utf-8")
    print("\nFixed case 74/M/10/23/1: raw=%.6f sigmoid=%.6f isotonic=%.6f"
          % (pfx_raw, pfx_sig, pfx_iso))

    # ---------------- README ----------------
    (OUT_DIR / "README.md").write_text(
        "# Phase 14 - Experimental Probability Recalibration Feasibility (Research Only)\n\n"
        "- Compares raw vs sigmoid(Platt) vs isotonic calibration on the frozen production LR\n"
        "  probability outputs. Underlying model never retrained.\n"
        "- Canonical 112/38 split; OOF raw probs (5-fold grouped CV, latest visit); second-level\n"
        "  grouped calibration CV for honest method selection; outer 38 used exactly once.\n"
        "- Threshold discipline: Option A preserves raw >= 0.40 screening decision; calibrated\n"
        "  display threshold = f(0.40). No recalibration integrated; production unchanged.\n"
        "- Isotonic flagged as unstable (Converted n=14). No commits.\n"
        "- Model version: binary_lr_latest_visit_v1. Features: age, sex, education_years, mmse, ses.\n",
        encoding="utf-8")

    print("\n=== ARTIFACTS ===")
    for f in sorted(p.name for p in OUT_DIR.iterdir()):
        print("  ", OUT_DIR / f)

    print("\n=== PRODUCTION SAFETY ===")
    print("production artifact md5 unchanged:", actual_md5 == EXPECTED_MD5)
    print("api.py/frontend/SHAP/threshold/best_model.pkl untouched")
    print("no commit made")


if __name__ == "__main__":
    main()